### ISSUE TITLE
wrong lazarus help download url

### ISSUE THREAD

**Issue by wkitty42** [LongDirtyAnimAlf/Reiniero-fpcup#22] opened 2016-06-22 10:25 UTC
> fpcup: info: helplazarus: documentation directory: /home/wkitty42/development/lazarus/fixes_1_4/docs/chm/
fpcup: info: Going to download /tmp/TMP00014.tmp.zip from URL: http://sourceforge.net/projects/lazarus/files/Lazarus%20Documentation/Lazarus%201.4/doc-chm_fpc2014_laz2015.zip/download
Executing : unzip "-o" "-j" "-d" "/home/wkitty42/development/lazarus/fixes_1_4/docs/chm/" "/tmp/TMP00014.tmp.zip" (working dir: )
Archive:  /tmp/TMP00014.tmp.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/TMP00014.tmp.zip or
        /tmp/TMP00014.tmp.zip.zip, and cannot find /tmp/TMP00014.tmp.zip.ZIP, period.
fpcup: WARNING: helplazarus: unzip failed with resultcode: 2304

it turns out that the file downloaded is html code and not a zip file at all...

> $ file /tmp/TMP00014.tmp.zip
/tmp/TMP00014.tmp.zip: HTML document, UTF-8 Unicode text, with very long lines

now what??

**Comment by LongDirtyAnimAlf** [comment] 2016-06-22 13:27
Could it be that you are using an old version of fpcup ?
Current versions use a very different version of the help-files.

**Comment by wkitty42** [comment] 2016-06-22 20:57
On 06/22/2016 09:27 AM, Don wrote:
> Could it be that you are using an old version of fpcup ?
> Current versions use a very different version of the help-files.

no, i explicitly updated to the latest fpcup before attempting to get my builds 
back in order so i could return to using trunk of both fpc and lazarus... that 
wasn't successful but i was able to get fpc 3.0.0 and lazarus 1.4 going... by 
building 2.6.4 with my 2.6.2 and then using that 2.6.4 to bootstrap 3.0.0... i 
can't get 3.1.1 (aka trunk) to compile, though... or maybe i did and it won't 
compile lazarus 1.7? i worked on it all night and finally went to bed this 
morning about 0700...

i do note that there is nothing in the new fpcup.ini file concerning lazarus 
1.6... wasn't it released before they went to 1.7? i had 1.5 before embarking on 
this update round...

**Comment by LongDirtyAnimAlf** [comment] 2016-06-24 06:55
You have to delete your old fpcup.ini !
Fpcup will generate a new (updated) fpcup.ini on first start if it does not detect an existing fpup.ini !
This is perhaps not the best way, but it is how BigChimp (the original author) has designed this.

**Comment by wkitty42** [comment] 2016-06-24 14:59
On 06/24/2016 02:55 AM, Don wrote:
> You have to delete your old fpcup.ini !
> Fpcup will generate a new (updated) fpcup.ini on first start if it does not
> detect an existing fpup.ini !

yes, i did that, too... before i created the issue, i worked my way through 
building fpc 2.6.4, and 3.0.0 with the latest (linux) version of fpcup... it was 
a slightly convoluted path because i had to build 2.6.4 with the existing 
bootstrap 2.6.2... then i copied that 2.6.4 into my bootstrap directory and this 
time built 3.0.0 which i also copied to my bootstrap directory in preparation 
for building trunk... i had to do this because there's apparently no official 
bootstrap compilers for 2.6.4 and 3.0.0 on x64 linux... i also received 
absolutely no responses from the fpc-devel list when i asked about the lack of 
bootstrap compilers for those versions... others exist but not for x64 linux :(


'
$ ls -la fpc*
-rwxrwxr-- 1 myuser myuser 1189560 Jun 20 10:30 fpclazup_linux_x64
lrwxrwxrwx 1 myuser myuser      15 Dec 27  2014 fpcup -> fpcup_linux_x64
-rw-rw-r-- 1 myuser myuser   22186 Dec 27  2014 fpcup_fpc-2.6.2.ini
-rw-rw-r-- 1 myuser myuser   40598 Jun 20 16:37 fpcup_fpc-2.6.4.ini
-rw-rw-r-- 1 myuser myuser   40598 Jun 21 10:03 fpcup.ini
-rwxrwxr-- 1 myuser myuser 1154672 Jun 20 10:30 fpcup_linux_x64
-rw-rw-r-- 1 myuser myuser   79749 Jun 22 07:27 fpcup.log
-rwx------ 1 myuser myuser     254 Jun 22 07:21 fpcup_update
-rwx------ 1 myuser myuser     141 Jun 21 08:45 fpcup_update-fpc2.6.4-nolaz
-rwx------ 1 myuser myuser     143 Jun 21 10:21 fpcup_update-fpcfixes3.0-nolaz
-rwx------ 1 myuser myuser     254 Jun 22 07:18 fpcup_update-fpc3.0.0-laz1.4
-rwx------ 1 myuser myuser     206 Jun 22 07:03 fpcup_update-fpctrunk-laz1.4
-rwx------ 1 myuser myuser     214 Jun 22 05:59 fpcup_update-fpctrunk-lazfixes1.4
'


fpcup_fpc-2.6.2.ini was my original fpcup.ini when i started this round of 
updating...

fpcup_fpc-2.6.4.ini is the fpcup.ini created with the latest version of 
fpcup_linux_x64... you can see that it is the same size as the fpcup.ini created 
a day later when i removed fpcup.ini again and let fpcup_linux_x64 generate 
another new one... i have not (ever) edited any of my fpcup related ini files...

i had decided that once i got fpc-3.0.0 in operation, that i would allow fpcup 
to build the help files stuff which is when i ran into this problem with the 
help file download URL...

i only use fpcup_linux_x64... i've never seen fpclazup_linux_x64 until this 
latest version of fpcup and i'm not sure what it is supposed to be used for...

my ultimate goal is to get back to fpc-trunk and lazarus-trunk at which time 
i'll have a fpcup_update-fpctrunk-laztrunk script to use for keeping them updated...

**Comment by LongDirtyAnimAlf** [comment] 2016-06-24 15:07
I will try to reproduce !

**Comment by wkitty42** [comment] 2016-06-29 13:56
@LongDirtyAnimAlf: any luck on this?

**Comment by LongDirtyAnimAlf** [comment] 2016-06-30 07:56
Sorry for let you waiting ... bit busy ...

I just ran the following command sequence:
`fpclazup_linux_x64 --fpcURL="trunk" --lazURL="trunk" --getfullrepo --verbose`

It gave me a fully working FPC and Lazarus trunk in my ~/development !

Also included was the latest help: 
```
fpclazup:` info: helplazarus: documentation directory: /home/superdad/development/lazarus/docs/chm/
fpclazup: info: Going to download /tmp/TMP00005.tmp.zip from URL: https://sourceforge.net/projects/lazarus/files/Lazarus%20Documentation/Lazarus%201.6/doc-chm-fpc3.0.0-laz1.6.zip/download
fpclazup: info: Download http(s) result: 200; for URL: http://internode.dl.sourceforge.net/project/lazarus/Lazarus%20Documentation/Lazarus%201.6/doc-chm-fpc3.0.0-laz1.6.zip
Executing : unzip "-o" "-j" "-d" "/home/superdad/development/lazarus/docs/chm/" "/tmp/TMP00005.tmp.zip" (working dir: )
```

So, I am not able to reproduce your problem !
I am sorry about that.

**Comment by wkitty42** [comment] 2016-06-30 14:56
@LongDirtyAnimAlf : no problem on being busy... i understand that completely...

on your test, you built for lazarus 1.6... the error is for lazarus 1.4...

why did i try to build 1.4? because the linux x86_64 version of fpcup does not list lazarus 1.6 in the ini file it creates... plus i was trying to work my way up through everything i had missed over the last year or two...

**Comment by LongDirtyAnimAlf** [comment] 2016-06-30 15:37
> my ultimate goal is to get back to fpc-trunk and lazarus-trunk

The above made me think that you wanted trunk !

My fpcup.ini (the one that is created by fpclazup):
```
[ALIASlazURL]
default=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_6
stable=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_6
trunk=http://svn.freepascal.org/svn/lazarus/trunk
; RC=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_8_RC1
1.7=http://svn.freepascal.org/svn/lazarus/trunk
1.6=http://svn.freepascal.org/svn/lazarus/branches/fixes_1_6
; fixes
fixes=http://svn.freepascal.org/svn/lazarus/branches/fixes_1_6
fixes1.6=http://svn.freepascal.org/svn/lazarus/branches/fixes_1_6
fixes1.4=http://svn.freepascal.org/svn/lazarus/branches/fixes_1_4

```
As you can see, a lot of 1.6 possibilities !
Again, I do not understand why your setup fails.

**Comment by wkitty42** [comment] 2016-06-30 18:57
On 06/30/2016 11:37 AM, Don wrote:
>> my ultimate goal is to get back to fpc-trunk and lazarus-trunk
>
> The above made me think that you wanted trunk !


sorry! i've been taking it one step at the time starting with the 2.6.2 
bootstrap compiler to build 2.6.4 and up from there...

> My fpcup.ini (the one that is created by fpclazup):


i just removed the fpcup.ini i had and ran fpcup again... if this is not the 
latest available build of fpcup, from where can it be gotten?

$ cat ~/fpcup_update-fpcfixes2.6-nolaz
#!/bin/sh
# shortcut generated by fcpup
"/home/myuser/fpcup_linux_x64" --fpcdir="/home/myuser/development/fpc/fixes2_6" 
--fpcURL="http://svn.freepascal.org/svn/fpc/branches/fixes_2_6/" --only=fpc $*

$ ~/fpcup_update-fpcfixes2.6-nolaz --verbose
fpcup
An FPC/Lazarus downloader/updater/installer
Open source freeware (modified LGPL/BSD)
Original by BigChimp: https://bitbucket.org/reiniero/fpcup
This version: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup

This program will download the FPC and Lazarus sources
from the source Subversion/SVN repositories,
compile, and install.
Result: you get a fresh, up-to-date Lazarus/FPC installation.

Version: based on commit fpcup001 (20150210)
Build date: 2015/07/12 12:30:29
Compiled for CPU: x86_64 on linux

fpcup: info: InstallerUniversal: no default source alias found: using fpcup default
fpcup: info: InstallerUniversal: no default source alias found: using fpcup default
Options:
Bootstrap compiler dir: /home/myuser/development/fpcbootstrap
Lazarus shortcut name:  Lazarus_fpcup
Shortcut fpcup name:    fpcup_update
FPC URL:                http://svn.freepascal.org/svn/fpc/branches/fixes_2_6/
FPC options:            -g -gl -O2 -Xs -CX -XX
FPC directory:          /home/myuser/development/fpc/fixes2_6
Lazarus directory:      /home/myuser/development/lazarus
Lazarus primary config path:
(Lazarus settings path) /home/myuser/development/config_lazarus
Lazarus URL:            http://svn.freepascal.org/svn/lazarus/branches/fixes_1_4
Lazarus options:        -g -gl -O2 -Xs -CX -XX
Keep local changes:     no
Re-apply local changes: yes
Log file name:          /home/myuser/fpcup.log

Effective parameters:
--fpcdir=/home/myuser/development/fpc/fixes2_6
--fpcURL=http://svn.freepascal.org/svn/fpc/branches/fixes_2_6/
--only=fpc
--verbose
Persistent parameters (can be saved in shell script):
--fpcdir="/home/myuser/development/fpc/fixes2_6" 
--fpcURL="http://svn.freepascal.org/svn/fpc/branches/fixes_2_6/"
WARNING: Limiting installation/update to fpc
Continue (Y/n): Y
[... trim ...]


> |[ALIASlazURL] default=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_6
> stable=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_6
> trunk=http://svn.freepascal.org/svn/lazarus/trunk ;
> RC=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_8_RC1
> 1.7=http://svn.freepascal.org/svn/lazarus/trunk
> 1.6=http://svn.freepascal.org/svn/lazarus/branches/fixes_1_6 ; fixes
> fixes=http://svn.freepascal.org/svn/lazarus/branches/fixes_1_6
> fixes1.6=http://svn.freepascal.org/svn/lazarus/branches/fixes_1_6
> fixes1.4=http://svn.freepascal.org/svn/lazarus/branches/fixes_1_4 |
>
> As you can see, a lot of 1.6 possibilities !
> Again, I do not understand why your setup fails.



my new fpcup.ini contains the following...

[ALIASlazURL]
default=http://svn.freepascal.org/svn/lazarus/branches/fixes_1_4
trunk=http://svn.freepascal.org/svn/lazarus/trunk
1.5=http://svn.freepascal.org/svn/lazarus/trunk
; Current stable:
1.4=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_4
fixes=http://svn.freepascal.org/svn/lazarus/branches/fixes_1_4
stable=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_4
; Older version for compatiblity with previous scripts
1.2.6=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_2_6
1.2.4=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_2_4
1.2.2=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_2_2
1.2.0=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_2_0
1.0.14=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_0_14
1.0.12=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_0_12
1.0.10=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_0_10
1.0.8=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_0_8
1.0.6=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_0_6
1.0.4=http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_0_4




-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list* unless
        private contact is specifically requested and granted.

**Comment by wkitty42** [comment] 2016-06-30 19:47
@LongDirtyAnimAlf  i'm testing this again... apparently my repo got out of whack... i've pulled everything again and now the ini file is showing the same options as your's does above... the ini file was starting to point to my recent update not being new enough... now i'm back to test this original issue and see if the help is handled properly... if this all works out, i'll close the issue...

**Comment by wkitty42** [comment] 2016-06-30 20:23
i don't think it is right...

`fpclazup: info: helplazarus: documentation directory: /home/wkitty42/development/lazarus/1_4/docs/chm/
fpclazup: info: Going to download /tmp/TMP00001.tmp.zip from URL: https://sourceforge.net/projects/lazarus/files/Lazarus%20Documentation/Lazarus%201.6/doc-chm-fpc3.0.0-laz1.6.zip/download
`

notice that we working in the lazarus/1_4/docs/chm directory but we're pulling the doc files from "Lazarus 1.6"...

**Comment by LongDirtyAnimAlf** [comment] 2016-07-01 11:39
Done. Please test !

**Comment by wkitty42** [comment] 2016-07-01 21:08
something is wrong... i have these packages installed already... had to have them for something else a long time back...

`
$ ~/fpcup_update-fpcfixes3.0-laz1.4 --verbose
Fpclazup, a FPC/Lazarus downloader/updater/installer
Original by BigChimp: https://bitbucket.org/reiniero/fpcup
This version: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup

Fpclazup will download the FPC and Lazarus sources
from the source SVN repositories, and compile, and install.
Result: you get a fresh, up-to-date Lazarus/FPC installation.

Version: based on commit fpcup001 (20150210)
Build date: 2016/07/01 13:34:25
Compiled for CPU: x86_64 on linux

Options:
Bootstrap dir:      /home/myuser/development/fpcbootstrap
FPC URL:            http://svn.freepascal.org/svn/fpc/tags/release_3_0_0
FPC options:        
FPC directory:      /home/myuser/development/fpc/fixes3_0
Lazarus URL:        http://svn.freepascal.org/svn/lazarus/tags/lazarus_1_4
Lazarus options:    
Lazarus directory:  /home/myuser/development/lazarus/1_4
Keep changes:       no
Re-apply changes:   no
Log file name:      /home/myuser/fpcup.log
Standard modules:   suggestedpackages
Standard modules:   lhelp
Standard modules:   lazdatadesktop
Standard modules:   doceditor

INFO: FPCUP will not download repos. It will only get the files !!!

Effective parameters:   
--fpcdir=/home/myuser/development/fpc/fixes3_0
--fpcURL=3.0
--lazdir=/home/myuser/development/lazarus/1_4
--lazURL=1.4
--skip=fpc
--verbose
Persistent parameters (can be saved in shell script):
--fpcdir="/home/myuser/development/fpc/fixes3_0" --lazdir="/home/myuser/development/lazarus/1_4" --fpcURL="3.0" --lazURL="1.4"
WARNING: Skipping installation/update of fpc
Continue (Y/n): Y
fpclazup: info: 1-7-16 16:51:52: fpcup fpcup001 (20150210) started.
fpclazup: info: Required -dev packages are not installed for Lazarus: libgtk2.0-dev
fpclazup: info: Required -dev packages are not installed for Lazarus: libgdk-pixbuf2.0-dev
fpclazup: info: Required -dev packages are not installed for Lazarus: libpango1.0-dev
fpclazup: info: Error running fpcup. Technical details: error executing sequence Default; line: 2, param: CheckDevLibs
Fpclazup failed.
`

`
$ dpkg-query -l libgtk2.0-dev; dpkg-query -l libgdk-pixbuf2.0-dev; dpkg-query -l libpango1.0-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                        Version                    Architecture               Description
+++-===========================================-==========================-==========================-===========================================================================================
ii  libgtk2.0-dev                               2.24.23-0ubuntu1.4         amd64                      development files for the GTK+ library

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                        Version                    Architecture               Description
+++-===========================================-==========================-==========================-===========================================================================================
ii  libgdk-pixbuf2.0-dev                        2.30.7-0ubuntu1.2          amd64                      GDK Pixbuf library (development files)

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                        Version                    Architecture               Description
+++-===========================================-==========================-==========================-===========================================================================================
ii  libpango1.0-dev                             1.36.3-1ubuntu1.1          amd64                      Development files for the Pango
`

**Comment by LongDirtyAnimAlf** [comment] 2016-07-02 06:23
Yep. You're right about library errors.
Library patch of yesterday reverted.

I am closing this issue now, because the original question about the help-version is solved.

**Closed by LongDirtyAnimAlf** 2016-07-02 06:23 UTC

**Comment by wkitty42** [comment] 2016-07-02 17:21
you asked me to test it and i haven't been able to do that yet... will update my repo now that the library stuff has been removed...
